apiVersion: v1
kind: Pod
metadata:
  name: fly-by-cnn-pod
spec:
  containers:
    - name: fly-by-cnn-container
      image: fly-by-cnn:2.0
      volumeMounts:
        - mountPath: "/shiny-tooth"
          name: shiny-tooth-storage
      command: ["sleep", "infinity"]
  volumes:
    - name: shiny-tooth-storage
      persistentVolumeClaim:
        claimName: shiny-tooth-claim


