FROM dcbia/fly-by-cnn:latest

RUN mkdir -p /app/.nvm

ENV NVM_DIR=/app/.nvm
ENV NODE_VERSION v14.16.0

RUN wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash \
	&& . $NVM_DIR/nvm.sh \
    && nvm install $NODE_VERSION \
    && npm i clusterpost-execution -g

ENV PATH=$NVM_DIR/versions/node/$NODE_VERSION/bin:$PATH
