FROM dcbia/fly-by-cnn:latest

WORKDIR /app

RUN wget https://github.com/RomainUSA/fly-by-cnn/releases/download/2.1.2/requirements.txt
RUN pip3 install -r /app/requirements.txt

RUN wget https://github.com/RomainUSA/fly-by-cnn/archive/refs/tags/2.1.2.zip
RUN unzip 2.1.2.zip
RUN rm -rf 2.1.2.zip 


RUN mkdir /app/models
WORKDIR /app/models

RUN wget https://github.com/RomainUSA/fly-by-cnn/releases/download/2.1.2/nnLU_model_5.hdf5
RUN wget https://github.com/RomainUSA/fly-by-cnn/releases/download/2.1.2/model_features.zip
RUN unzip model_features.zip
RUN rm -rf model_features.zip


WORKDIR /app
RUN wget https://github.com/RomainUSA/fly-by-cnn/releases/download/2.1.2/groundtruth.zip
RUN unzip groundtruth.zip
RUN rm -rf groundtruth.zip

RUN mkdir /app/data
RUN mkdir /app/data/input
RUN mkdir /app/data/uid
RUN mkdir /app/data/out_tmp
RUN mkdir /app/data/merged
RUN mkdir /app/data/out







