apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shiny-tooth-claim
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
